c_stdlib_version:          # [osx]
  - "10.13"                # [osx and x86_64]
  - "11.0"                 # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "10.13"                # [osx and x86_64]
  - "11.0"                 # [osx and arm64]
