MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "10.12"                # [osx and x86_64]
  - "11.0"                 # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "10.12"                # [osx and x86_64]
  - "11.0"                 # [osx and arm64]
