{% set version = "1.0.6" %}

package:
  name: kmedoids
  version: {{ version }}

source:
  url: https://github.com/kno10/python-kmedoids/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec61af7c649ed1088f492da8c6b9f8ea8296d06079dc8b5589893550e3e09a57

build:
  number: 0
  script:
    - export CARGO_NET_GIT_FETCH_WITH_CLI=true
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }} # used by Rust
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - kmedoids
    - kmedoids.kmedoids
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - cd tests && python -m unittest discover

about:
  home: https://github.com/kno10/python-kmedoids
  summary: k-Medoids Clustering in Python with FasterPAM
  description: This python package implements k-medoids clustering with PAM and variants of clustering by direct optimization of the (Medoid) Silhouette. It can be used with arbitrary dissimilarites, as it only requires a dissimilarity matrix as input. A sklearn compatible API is included.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  doc_url: https://python-kmedoids.readthedocs.io/
  dev_url: https://github.com/kno10/python-kmedoids

extra:
  recipe-maintainers:
    - kno10
    - lale1009
