{% set version = "0.5.2" %}

package:
  name: kmedoids
  version: {{ version }}

source:
  url: https://github.com/kno10/python-kmedoids/archive/refs/tags/v{{ version }}.tar.gz
  sha256: db6ea3145fdb933d6872700957d600cd0949e1cd120e073aff26ad2bb736f12b

build:
  number: 0
  script:
    - export CARGO_NET_GIT_FETCH_WITH_CLI=true
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]  
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - python
    - pip
    - numpy
    - maturin
  run:
    - python
    - numpy <2 # https://github.com/PyO3/rust-numpy/issues/409

test:
  imports:
    - kmedoids
    - kmedoids.kmedoids
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - cd tests && python -m unittest discover

about:
  home: https://github.com/kno10/python-kmedoids
  summary: 'k-Medoids Clustering in Python with FasterPAM'
  description:
    This python package implements k-medoids clustering with PAM and
    variants of clustering by direct optimization of the (Medoid) Silhouette,
    including the DynMSC variant that automatically chooses the number
    of clusters (based on the optimum medoid silhouette).
    It can be used with arbitrary dissimilarites, as it only requires
    a dissimilarity matrix as input. A sklearn compatible API is included.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  doc_url: https://python-kmedoids.readthedocs.io/
  dev_url: https://github.com/kno10/python-kmedoids

extra:
  recipe-maintainers:
    - kno10
    - larslenssen
